# Generated by Django 6.0.3 on 2026-03-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_user_type_customuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('STUDENTS', 'students'), ('STAFFS', 'staffs'), ('ADMIN', 'admin')], default='STUDENTS', max_length=20),
        ),
    ]
