# Generated by Django 6.0.3 on 2026-04-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_category_options_item_dropped_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='picked_up_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
