# Generated by Django 6.0.3 on 2026-04-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_picked_up_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='claimed_by',
            field=models.CharField(blank=True, help_text='Student ID of the person who claimed this item', max_length=100, null=True),
        ),
    ]
