# Generated by Django 6.0.3 on 2026-04-24 14:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_claimed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('picked_up_date', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('colour', models.CharField(blank=True, max_length=50)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('date_reported', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('found', 'Found'), ('claimed', 'Claimed'), ('returned', 'Returned')], default='found', max_length=20)),
                ('claimed_by', models.CharField(blank=True, help_text='Student ID of the person who claimed this item', max_length=100, null=True)),
            ],
            options={
                'ordering': ['-date_reported'],
            },
        ),
        migrations.CreateModel(
            name='LostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('colour', models.CharField(blank=True, max_length=50)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('date_reported', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('claimed', 'Claimed')], default='pending', max_length=20)),
            ],
            options={
                'ordering': ['-date_reported'],
            },
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='items_item_status_819478_idx',
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='items_item_categor_ac6954_idx',
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='items_item_date_re_f6a61b_idx',
        ),
        migrations.AddField(
            model_name='foundreport',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.category'),
        ),
        migrations.AddField(
            model_name='foundreport',
            name='dropped_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dropped_found_items', to='items.location'),
        ),
        migrations.AddField(
            model_name='foundreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lostreport',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.category'),
        ),
        migrations.AddField(
            model_name='lostreport',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.location'),
        ),
        migrations.AddField(
            model_name='lostreport',
            name='matched_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='items.foundreport'),
        ),
        migrations.AddField(
            model_name='lostreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foundreport',
            name='matched_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='items.lostreport'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='dropped_location',
        ),
        migrations.RemoveField(
            model_name='item',
            name='location',
        ),
        migrations.RemoveField(
            model_name='item',
            name='matched_with',
        ),
        migrations.RemoveField(
            model_name='item',
            name='reporter',
        ),
        migrations.AddIndex(
            model_name='lostreport',
            index=models.Index(fields=['status'], name='items_lostr_status_f334b8_idx'),
        ),
        migrations.AddIndex(
            model_name='lostreport',
            index=models.Index(fields=['category'], name='items_lostr_categor_896f0a_idx'),
        ),
        migrations.AddIndex(
            model_name='lostreport',
            index=models.Index(fields=['date_reported'], name='items_lostr_date_re_593114_idx'),
        ),
        migrations.AddIndex(
            model_name='foundreport',
            index=models.Index(fields=['status'], name='items_found_status_68d912_idx'),
        ),
        migrations.AddIndex(
            model_name='foundreport',
            index=models.Index(fields=['category'], name='items_found_categor_60794a_idx'),
        ),
        migrations.AddIndex(
            model_name='foundreport',
            index=models.Index(fields=['date_reported'], name='items_found_date_re_62f092_idx'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
