# Generated by Django 6.0.3 on 2026-04-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_foundreport_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundreport',
            name='description',
            field=models.TextField(help_text='Provide a detailed description of the item, including any unique features or identifiers and additional information on location.'),
        ),
        migrations.AlterField(
            model_name='foundreport',
            name='status',
            field=models.CharField(choices=[('found', 'Found'), ('matched', 'Matched'), ('claimed', 'Claimed'), ('returned', 'Returned')], default='found', max_length=20),
        ),
        migrations.AlterField(
            model_name='foundreport',
            name='title',
            field=models.CharField(help_text="Provide a brief title for the item, e.g. 'Black iPhone 12 on' or 'Blue Backpack'.", max_length=200),
        ),
    ]
